INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1, 2, N'Toiletten Smaland', N'toi       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (2, 2, N'Baby verschoonruimte', N'bab       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (3, 2, N'Toiletten dames klanten', N'dam       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (4, 2, N'Was- en kleedruimte keukenpersoneel', N'waskleed  ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (5, 2, N'Toiletten heren klanten', N'her       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (6, 2, N'Toiletten minder validen', N'miv       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (7, 2, N'Toiletten dames personeel', N'toildamper', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (8, 2, N'Keukenvloer productielijn', N'keu       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (10, 2, N'Smaland', N'sma       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (11, 2, N'Gang nood', N'gan       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (12, 2, N'Klantenrestaurant', N'kla       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (13, 2, N'Personeelsrestaurant', N'perA      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (14, 2, N'Rookruimte', N'roo       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (15, 2, N'Gang bij klantentoiletten', N'ganb      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (16, 2, N'Kantoor keuken', N'kan       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (17, 2, N'Sweden shop', N'swe       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (19, 2, N'Sweden shop magazijn', N'swes      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (20, 2, N'Bistro counter', N'bis       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (21, 2, N'Bistro eetgedeelte', N'bise      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (22, 2, N'EHBO ruimte', N'ehb       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (23, 2, N'Was- en kleedruimten personeel', N'wasklepers', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (24, 2, N'Entree draaideur', N'dra       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (25, 2, N'Entree hal', N'ent       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (26, 2, N'Winkelwagenruimte Market hall', N'wwruimteMH', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (27, 2, N'Lift naar showroom', N'lif       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (28, 2, N'Entreegebied showroom', N'ents      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (29, 2, N'Showroom', N'sho       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (30, 2, N'Market hall', N'mar       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (31, 2, N'Entreegebied Market hall', N'entm      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (32, 2, N'Trappen naar Market hall', N'tra       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (33, 2, N'Magazijn zelfbediening', N'zel       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (34, 2, N'Kassagebied', N'kas       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (36, 2, N'Wachtruimte Customer Service', N'wac       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (37, 2, N'Uitgangsgebied', N'uit       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (38, 2, N'Winkelwagenruimte entreegebied', N'wentree   ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (39, 2, N'Vergaderruimten', N'ver       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (40, 2, N'Receptie', N'rec       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (41, 2, N'Kantoor Customer Service', N'kanCS     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (42, 2, N'Personeelsingang', N'perAA     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (43, 2, N'Gang keukenpersoneel', N'gank      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (44, 2, N'Goederenontvangst Customer Service', N'ganCS     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (45, 2, N'Roltrappen', N'roltr     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (46, 2, N'Liften', N'lifA      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (47, 2, N'Werkruimte schoonmaak', N'wer       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (48, 2, N'Magazijn', N'mag       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (49, 2, N'Goederenontvangst', N'goeA      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (50, 2, N'Kantoor goederenstroom', N'kang      ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (51, 2, N'Montageruimte', N'mon       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (52, 2, N'Magazijn retouren', N'magret    ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (53, 2, N'IT ruimte', N'it        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (54, 2, N'Trappen nood', N'noodtr    ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (55, 4, N'Aula', N'Aul       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (56, 4, N'Bureaukamer', N'Bur       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (57, 4, N'Doucheruimte', N'Dou       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (58, 4, N'Entrée', N'Ent       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (59, 4, N'Gang', N'Gan       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (60, 4, N'Gym/-sportzaal', N'Gym       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (61, 4, N'Hal', N'Hal       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (62, 4, N'Handenarbeid', N'Han       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (63, 4, N'Kelderbox', N'Kel       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (64, 4, N'Keuken/pantry', N'Keu       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (65, 4, N'Kleedruimte', N'Kle       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (66, 4, N'Leslokaal', N'Les       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (67, 4, N'Lift', N'Lif       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (68, 4, N'Personeelsruimte', N'Per       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (69, 4, N'Restaurant', N'Res       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (70, 4, N'Speellokaal', N'Spe       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (71, 4, N'Toilet', N'Toi       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (72, 4, N'Trap-Trappenhuis', N'Tra       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (73, 4, N'Vergader/spreekruimte', N'Ver       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (74, 4, N'Wasruimte', N'Was       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (78, 2, N'Toiletten heren personeel', N'toilherper', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (79, 2, N'Gangen personeelsgebied', N'gpers     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (82, 2, N'Werkruimte Comm&In', N'wci       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (83, 2, N'Trappen personeelsingang', N'tperi     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (84, 2, N'Kantoorgebied (Staff, Comm&In)', N'kanSCI    ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (85, 2, N'Gangen personeelsrestaurant', N'ganpr     ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (86, 2, N'Winkelwagenruimte magazijn zelfbediening', N'wmz       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (89, 4, N'Ontvangst-/ wachtruimte', N'Ont       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (90, 4, N'Repro-/printruimte', N'Rep       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (91, 4, N'Garderobe', N'Gar       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1095, 4, N'Bibliotheek', N'Bib       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1111, 4, N'Buitenbordes', N'Bui       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1112, 4, N'Pompruimte', N'Pom       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1113, 4, N'Werkplaats', N'Wer       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1114, 4, N'Besturingsruimte', N'Bes       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1115, 4, N'Zaal', N'za        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1116, 4, N'Zwembad', N'zie       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1117, 4, N'Fitness', N'fit       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1118, 4, N'Wellness', N'wel       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1119, 4, N'Behandel- onderzoek', N'beh       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1120, 4, N'OK', N'ok        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1121, 4, N'Praktijklokaal', N'Pro       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1122, 4, N'Lab- onderzoek ruimte', N'lab       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1123, 4, N'Groepsruimte', N'gro       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1124, 4, N'Paskamer', N'psk       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1125, 4, N'Logistiek', N'Log       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1126, 4, N'Datacentre', N'Dat       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1127, 4, N'Kantine', N'Knt       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1128, 4, N'Parkeerterrein', N'par       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1129, 4, N'Rookruimte', N'rk        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1130, 4, N'Fietsenstalling', N'Fst       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1131, 4, N'Telefoonkast', N'Tk        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1132, 4, N'Lounge ruimte', N'Lou       ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1133, 4, N'Productieruimte', N'pr        ', 1)
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1134, 4, N'Representatieve ruimte', N'rp        ', 1)