INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1, 2, 'Toiletten Smaland', 'toi       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (2, 2, 'Baby verschoonruimte', 'bab       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (3, 2, 'Toiletten dames klanten', 'dam       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (4, 2, 'Was- en kleedruimte keukenpersoneel', 'waskleed  ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (5, 2, 'Toiletten heren klanten', 'her       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (6, 2, 'Toiletten minder validen', 'miv       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (7, 2, 'Toiletten dames personeel', 'toildamper', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (8, 2, 'Keukenvloer productielijn', 'keu       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (10, 2, 'Smaland', 'sma       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (11, 2, 'Gang nood', 'gan       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (12, 2, 'Klantenrestaurant', 'kla       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (13, 2, 'Personeelsrestaurant', 'perA      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (14, 2, 'Rookruimte', 'roo       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (15, 2, 'Gang bij klantentoiletten', 'ganb      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (16, 2, 'Kantoor keuken', 'kan       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (17, 2, 'Sweden shop', 'swe       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (19, 2, 'Sweden shop magazijn', 'swes      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (20, 2, 'Bistro counter', 'bis       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (21, 2, 'Bistro eetgedeelte', 'bise      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (22, 2, 'EHBO ruimte', 'ehb       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (23, 2, 'Was- en kleedruimten personeel', 'wasklepers', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (24, 2, 'Entree draaideur', 'dra       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (25, 2, 'Entree hal', 'ent       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (26, 2, 'Winkelwagenruimte Market hall', 'wwruimteMH', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (27, 2, 'Lift naar showroom', 'lif       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (28, 2, 'Entreegebied showroom', 'ents      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (29, 2, 'Showroom', 'sho       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (30, 2, 'Market hall', 'mar       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (31, 2, 'Entreegebied Market hall', 'entm      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (32, 2, 'Trappen naar Market hall', 'tra       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (33, 2, 'Magazijn zelfbediening', 'zel       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (34, 2, 'Kassagebied', 'kas       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (36, 2, 'Wachtruimte Customer Service', 'wac       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (37, 2, 'Uitgangsgebied', 'uit       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (38, 2, 'Winkelwagenruimte entreegebied', 'wentree   ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (39, 2, 'Vergaderruimten', 'ver       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (40, 2, 'Receptie', 'rec       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (41, 2, 'Kantoor Customer Service', 'kanCS     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (42, 2, 'Personeelsingang', 'perAA     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (43, 2, 'Gang keukenpersoneel', 'gank      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (44, 2, 'Goederenontvangst Customer Service', 'ganCS     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (45, 2, 'Roltrappen', 'roltr     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (46, 2, 'Liften', 'lifA      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (47, 2, 'Werkruimte schoonmaak', 'wer       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (48, 2, 'Magazijn', 'mag       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (49, 2, 'Goederenontvangst', 'goeA      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (50, 2, 'Kantoor goederenstroom', 'kang      ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (51, 2, 'Montageruimte', 'mon       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (52, 2, 'Magazijn retouren', 'magret    ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (53, 2, 'IT ruimte', 'it        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (54, 2, 'Trappen nood', 'noodtr    ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (55, 4, 'Aula', 'Aul       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (56, 4, 'Bureaukamer', 'Bur       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (57, 4, 'Doucheruimte', 'Dou       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (58, 4, 'Entrée', 'Ent       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (59, 4, 'Gang', 'Gan       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (60, 4, 'Gym/-sportzaal', 'Gym       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (61, 4, 'Hal', 'Hal       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (62, 4, 'Handenarbeid', 'Han       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (63, 4, 'Kelderbox', 'Kel       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (64, 4, 'Keuken/pantry', 'Keu       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (65, 4, 'Kleedruimte', 'Kle       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (66, 4, 'Leslokaal', 'Les       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (67, 4, 'Lift', 'Lif       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (68, 4, 'Personeelsruimte', 'Per       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (69, 4, 'Restaurant', 'Res       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (70, 4, 'Speellokaal', 'Spe       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (71, 4, 'Toilet', 'Toi       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (72, 4, 'Trap-Trappenhuis', 'Tra       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (73, 4, 'Vergader/spreekruimte', 'Ver       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (74, 4, 'Wasruimte', 'Was       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (78, 2, 'Toiletten heren personeel', 'toilherper', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (79, 2, 'Gangen personeelsgebied', 'gpers     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (82, 2, 'Werkruimte Comm&In', 'wci       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (83, 2, 'Trappen personeelsingang', 'tperi     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (84, 2, 'Kantoorgebied (Staff, Comm&In)', 'kanSCI    ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (85, 2, 'Gangen personeelsrestaurant', 'ganpr     ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (86, 2, 'Winkelwagenruimte magazijn zelfbediening', 'wmz       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (89, 4, 'Ontvangst-/ wachtruimte', 'Ont       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (90, 4, 'Repro-/printruimte', 'Rep       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (91, 4, 'Garderobe', 'Gar       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1095, 4, 'Bibliotheek', 'Bib       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1111, 4, 'Buitenbordes', 'Bui       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1112, 4, 'Pompruimte', 'Pom       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1113, 4, 'Werkplaats', 'Wer       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1114, 4, 'Besturingsruimte', 'Bes       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1115, 4, 'Zaal', 'za        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1116, 4, 'Zwembad', 'zie       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1117, 4, 'Fitness', 'fit       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1118, 4, 'Wellness', 'wel       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1119, 4, 'Behandel- onderzoek', 'beh       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1120, 4, 'OK', 'ok        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1121, 4, 'Praktijklokaal', 'Pro       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1122, 4, 'Lab- onderzoek ruimte', 'lab       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1123, 4, 'Groepsruimte', 'gro       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1124, 4, 'Paskamer', 'psk       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1125, 4, 'Logistiek', 'Log       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1126, 4, 'Datacentre', 'Dat       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1127, 4, 'Kantine', 'Knt       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1128, 4, 'Parkeerterrein', 'par       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1129, 4, 'Rookruimte', 'rk        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1130, 4, 'Fietsenstalling', 'Fst       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1131, 4, 'Telefoonkast', 'Tk        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1132, 4, 'Lounge ruimte', 'Lou       ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1133, 4, 'Productieruimte', 'pr        ', 1);
INSERT INTO AreaDescriptions (Id, ModuleId, Name, Abbreviation, Active) VALUES (1134, 4, 'Representatieve ruimte', 'rp        ', 1);